name: Build Web
description: Build Web
runs:
  using: "composite"
  steps:
    - name: Out cache Web
      uses: actions/cache@v4
      id: out-cache
      with:
        path: redot-engine/redot-engine/out/web
        key: out-web-${{env.redot-BASE_VERSION}}
        restore-keys: |
          out-web-${{env.redot-BASE_VERSION}}

    - name: Build Macos
      shell: bash
      run: |      
        declare -a JOBS=(
          "target=template_debug"
          "target=template_release"
          "target=template_debug dlink_enabled=yes"
          "target=template_release dlink_enabled=yes"
        )
        declare -a JOBS_NOTHREADS=(
          "target=template_debug threads=no"
          "target=template_release threads=no"
          "target=template_debug dlink_enabled=yes threads=no"
          "target=template_release dlink_enabled=yes threads=no"
        )
        
        source /root/emsdk/emsdk_env.sh
        
        echo "Starting classical build for Web..."
        
        for i in {0..3}; do
          cp -r redot-engine redot-engine$i
          cd redot-engine$i
          echo "$SCONS platform=web ${OPTIONS} ${JOBS[$i]}"
          $SCONS platform=web ${OPTIONS} ${JOBS[$i]} &
          pids[$i]=$!
          cd ..
        done
      
        cd redot-engine
        echo "$SCONS platform=web ${OPTIONS} target=editor use_closure_compiler=yes"
        $SCONS platform=web ${OPTIONS} target=editor use_closure_compiler=yes &
        pid_editor=$!
      
        for pid in ${pids[*]}; do
          wait $pid
        done
        wait $pid_editor
      
        cd ..
        for i in {0..3}; do
          cp -r redot-engine redot-engine-nothreads$i
          cd redot-engine-nothreads$i
          echo "$SCONS platform=web ${OPTIONS} ${JOBS_NOTHREADS[$i]}"
          $SCONS platform=web ${OPTIONS} ${JOBS_NOTHREADS[$i]} &
          pids_nothreads[$i]=$!
        done
      
        for pid in ${pids_nothreads[*]}; do
          wait $pid
        done
      
        mkdir -p redot-engine/out/web/tools
        cp -rvp redot-engine/bin/*.editor*.zip redot-engine/out/web/tools
      
        mkdir -p redot-engine/out/web/templates
        for i in {0..3}; do
          cp -rvp redot-engine$i/bin/*.zip redot-engine/out/web/templates
          cp -rvp redot-engine-nothreads$i/bin/*.zip redot-engine/out/web/templates
        done
        
        echo "Starting Mono build for Web..."
      
        cp -r mono-glue/GodotSharp/GodotSharp/Generated modules/mono/glue/GodotSharp/GodotSharp/
      
        $SCONS platform=web ${OPTIONS} ${OPTIONS_MONO} target=template_debug
        $SCONS platform=web ${OPTIONS} ${OPTIONS_MONO} target=template_release
      
        mkdir -p redot-engine/out/web/templates-mono
        cp -rvp bin/*.zip redot-engine/out/web/templates-mono
        rm -f bin/*.zip
