name: Redot Build Images
on:
  workflow_dispatch:
    inputs:
      redot-version:
        description: "Redot version eg 4.3"
        required: true
        type: string
        default: "4.3"
      fedora-version:
        description: "Fedora version, yea yea Fedora sucks eg 40"
        required: true
        type: string
        default: "40"

env:
  REGISTRY: ghcr.io
  ORG: trashguy

jobs:
  base:
    name: Build Base Images
    runs-on: "ubuntu-latest"

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG }}/redot-base

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: images/base.Dockerfile
          context: ./images
          push: true
          build-args: |
            fedora_version=${{ github.event.inputs.fedora-version }}
          tags: ${{ env.REGISTRY }}/${{ env.ORG}}/redot-fedora:${{ github.event.inputs.redot-version }}-${{ github.event.inputs.fedora-version }}

  not-apple:
    needs: base
    name: Build Non Apple images
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include:
          - name: android
          - name: linux
          - name: web
          - name: windows

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG }}/redot-base

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: images/${{ matrix.name }}.Dockerfile
          context: ./images
          push: true
          build-args: |
            source_image=${{ env.REGISTRY }}/${{ env.ORG}}/redot-fedora:${{ github.event.inputs.redot-version }}-${{ github.event.inputs.fedora-version }}
          tags: ${{ env.REGISTRY }}/${{ env.ORG}}/redot-${{ matrix.name }}:${{ github.event.inputs.redot-version }}-${{ github.event.inputs.fedora-version }}
