name: Redot Build Toolchains
on:
  workflow_dispatch:
    inputs:
      make-release:
        description: "Build a release"
        required: true
        type: boolean
        default: false

jobs:
